#禁止修改本文件
#禁止修改本文件
#禁止修改本文件
#禁止修改本文件
#禁止修改本文件
spring:
  profiles:
    active: dev

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 跨域允许源，多个地址逗号分隔
cors:
  allow-origins: http://localhost:5173,http://localhost:5174
